settings:
  docker:
    parent_image: 
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  # Data ETL & Feature engineering pipelines parameters
  author_links:
    - user_full_name: Abhinav Kumar # [First Name(s)] [Last Name]
      links:
        # Medium (only articles that are not under the paid wall work)
        - https://medium.com/@abhinav.mg.k/using-oops-and-software-design-patterns-in-machine-learning-part-1-75ef5b3c28f6
        - https://medium.com/@abhinav.mg.k/creating-a-preference-dataset-with-llama-3-1-70b-and-ollama-d16f37019eb5
        - https://medium.com/@abhinav.mg.k/coding-a-large-language-model-from-scratch-part-1-216c859346ea
    
        
  # Generate instruct dataset pipeline parameters
  test_split_size: 0.1
  push_to_huggingface: false
  dataset_id: abhinavkumar/cowriter
  mock: false