settings:
  docker:
    parent_image: 
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  artifact_names:
    - raw_documents
    - cleaned_documents
    - instruct_datasets
    - preference_datasets
