settings:
  docker:
    parent_image: 
    skip_build: True
  orchestrator.sagemaker:
    synchronous: false

parameters:
  test_split_size: 0.05
  dataset_type: "preference"
  push_to_huggingface: true
  dataset_id: abhinavkumar/cowriter-dpo
  mock: false
